# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='rsa_pass',
            field=models.CharField(default='', max_length=64, verbose_name='私钥的密钥'),
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='sn_key',
            field=models.CharField(default='', max_length=256, verbose_name='唯一设备ID'),
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='ssh_host_port',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='ssh登录的端口'),
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='ssh_hostip',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='ssh登录的ip'),
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='ssh_rsa',
            field=models.CharField(default='', max_length=64, verbose_name='ssh私钥'),
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='ssh_username',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='ssh用户名'),
        ),
        migrations.AlterField(
            model_name='connectioninfo',
            name='ssh_userpasswd',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='ssh用户密码'),
        ),
        migrations.AlterField(
            model_name='netconnectioninfo',
            name='sn_key',
            field=models.CharField(default='', max_length=256, verbose_name='唯一设备ID'),
        ),
        migrations.AlterField(
            model_name='netconnectioninfo',
            name='tel_enpasswd',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='设备超级用户密码'),
        ),
        migrations.AlterField(
            model_name='netconnectioninfo',
            name='tel_host_port',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='设备登录的端口'),
        ),
        migrations.AlterField(
            model_name='netconnectioninfo',
            name='tel_hostip',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='设备登录的ip'),
        ),
        migrations.AlterField(
            model_name='netconnectioninfo',
            name='tel_username',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='netconnectioninfo',
            name='tel_userpasswd',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='设备用户密码'),
        ),
        migrations.AlterField(
            model_name='networkinfo',
            name='sn',
            field=models.CharField(default='', max_length=256, verbose_name='SN－设备的唯一标识'),
        ),
        migrations.AlterField(
            model_name='othermachineinfo',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='othermachineinfo',
            name='reson_str',
            field=models.CharField(default='', max_length=128, verbose_name='归纳原因'),
        ),
        migrations.AlterField(
            model_name='physicalserverinfo',
            name='mac',
            field=models.CharField(default='', max_length=512, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='physicalserverinfo',
            name='machine_brand',
            field=models.CharField(default='--', max_length=60, verbose_name='服务器品牌'),
        ),
        migrations.AlterField(
            model_name='physicalserverinfo',
            name='sn',
            field=models.CharField(default='', max_length=256, verbose_name='SN-主机的唯一标识'),
        ),
        migrations.AlterField(
            model_name='physicalserverinfo',
            name='system_ver',
            field=models.CharField(default='', max_length=30, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='physicalserverinfo',
            name='vir_type',
            field=models.CharField(default='', max_length=2, verbose_name='宿主机类型'),
        ),
        migrations.AlterField(
            model_name='statisticsrecord',
            name='datatime',
            field=models.DateTimeField(default='2019-10-23', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='virtualserverinfo',
            name='mac',
            field=models.CharField(default='', max_length=512, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='virtualserverinfo',
            name='server_type',
            field=models.CharField(default='', max_length=80, verbose_name='服务器类型:kvm,Vmware,Docker,others'),
        ),
        migrations.AlterField(
            model_name='virtualserverinfo',
            name='sn',
            field=models.CharField(default='', max_length=256, verbose_name='SN-主机的唯一标识'),
        ),
        migrations.AlterField(
            model_name='virtualserverinfo',
            name='system_ver',
            field=models.CharField(default='', max_length=30, verbose_name='操作系统版本'),
        ),
    ]
